version: "2"

volumes:
  mysql:
  project:
  results:
  sshgrid:

services:
  mysql:
    image: boinc/server_mysql:latest
    build: images/mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  makeproject:
    image: boinc/server_makeproject:latest-b2d
    build: 
      context: images/makeproject
      dockerfile: Dockerfile.b2d
    hostname: boincserver
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"

  apache:
    image: boinc/server_apache:latest-b2d
    build: 
      context: images/apache
      dockerfile: Dockerfile.b2d
    hostname: boincserver
    network_mode: bridge
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "sshgrid:/sshgrid"
    ports: 
     - "80:80"
    tty: true
    
  sshgrid:
    image: boinc/server_sshgrid:latest
    build: 
      context: images/sshgrid
      dockerfile: Dockerfile
    hostname: boincserver
    network_mode: bridge
    links:
     - mysql
    volumes: 
     - "sshgrid:/sshgrid"
    ports: 
     - "422:22"
    tty: true
