version: "3"

services:
  makeproject:
    volumes:
     - "project:/root/project.dst"
     - "$BOINC_SRC_DIR:/root/boinc"
    working_dir: /root/boinc
    entrypoint: devproject.sh
    command: bash -c "./_autosetup && ./configure --disable-manager --disable-client && make"
